### ISSUE TITLE
why you have kept, NOSCAN=1?

### ISSUE THREAD

**Issue by ajaymalikbol** [srcclr/agent-docker#1] opened 2020-06-09 13:22 UTC
curl -sSL https://download.sourceclear.com/ci.sh | CACHE_DIR=/tmp NOSCAN=1 bash

by default value of NOSCAN=0, why you have kept it 1

**Comment by dariusf** [comment] 2020-06-09 15:12
We do that in the Dockerfile just for the side effect of installing the agent. It only runs later, when a container is created.

**Comment by jsyeo** [comment] 2020-06-10 04:08
Closing because not a bug or an issue.

**Closed as completed by jsyeo** 2020-06-10 04:08 UTC
